const ActionTypes = {
  FINISH_LOADING_ALL_MEMBERS: 'FINISH_LOADING_ALL_MEMBERS',
  SET_MEMBERS: 'SET_MEMBERS',
  START_LOADING_ALL_MEMBERS: 'START_LOADING_ALL_MEMBERS',
};

export default ActionTypes;
